#!/usr/bin/env sh

# Run this script from the repo root folder to:
# - Build a Docker container with Python 3.
# - Install Python packages from requirements.txt.
# - Launch a Jupyter notebook server on port 8888 in a container.
# - Bind-mount folders to be accessed from inside the container.
# - Delete the container when it stops.

REPO=${PWD}

docker build --tag "braidcoin:latest" "${REPO}" &&
#docker run --rm "braidcoin:latest" pip freeze > requirements.txt &&
docker run --rm \
  --user 1001 \
  --hostname "braidcoin" \
  --publish "127.0.0.1:8888:8888" \
  --volume "${REPO}/.ipython:/home/braidcoin/.ipython" \
  --volume "${REPO}/.jupyter:/home/braidcoin/.jupyter" \
  --volume "${REPO}/books:/home/braidcoin/books" \
  --volume "${REPO}/code:/home/braidcoin/code" \
  --volume "${REPO}/output:/home/braidcoin/output" \
  "braidcoin:latest" \
  jupyter notebook --no-browser --ip=0.0.0.0 --port=8888
